### ISSUE TITLE
macOS Updater Utility (mUU) v.14.2 - hubcli incorrect command on Sequoia v.15.0.1

### ISSUE THREAD

**Issue by ThePirat91** [euc-oss/euc-samples#20]
Hello, we tried to upgrade a 2020 MacBook Air M1 from macOS 15.0.1 to 15.1 via MUU, but we get the error below.

<img width="1552" alt="Screenshot 2024-10-31 at 11 48 33" src="https://github.com/user-attachments/assets/1e53d2e6-9aaa-411f-ad22-2c84850adbd4">

We are using the latest version of the .plist reported on this repo, with the "latest" desidedOSversion key.

![image](https://github.com/user-attachments/assets/3a0a37d0-01a6-4d89-93a9-081f29d53146)

Thanks

**Comment by ThePirat91** [comment]
UPDATE

We tried editing the .plist, setting the “desidedOSversion” key specifically to version 15.1, and this time the command seemed to be sent correctly.


<img width="1552" alt="Screenshot 2024-10-31 at 12 17 59" src="https://github.com/user-attachments/assets/671b2724-43db-484d-9e4c-b39d065511cc">


At this point the problem would appear to be related to the use of the value “latest.”

**Comment by mzaske3** [comment]
Thanks for the feedback, looks to be caused by the different builds of 15.1. I have fixed this in rev 14.3 that is awaiting merge: https://github.com/euc-oss/euc-samples/pull/21

**Comment by ThePirat91** [comment]
Thank you for the prompt response. We will test the new version and come back with a feedback about it.
