### ISSUE TITLE
Use Initialize- instead of Rebuild- in Omnissa.Horizon.Helper

### ISSUE THREAD

**Issue by B-Art** [euc-oss/euc-samples#23]
WARNING: The names of some imported commands from the module 'Omnissa.Horizon.Helper' include unapproved verbs that might make them less discoverable. To find the commands with ...
unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
VERBOSE: The 'Rebuild-HVMachine' command in the Omnissa.Horizon.Helper' module was imported, but because its name does not include an approved verb, it might be difficult to   ...
find. The suggested alternative verbs are "Initialize".

**Comment by helmlingp** [comment]
Thanks for the comment @B-Art, the engineers should be looking at this in coming releases, but this is a very common issuue with powershell and likely not going to change.
